my:
  jwt_pwd: abc123
spring:
  application:
    name: weibo
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/weibo?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

server:
  port: 8080
  servlet:
    context-path: /